
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    console.log('=== EDGE FUNCTION STARTED ===');
    console.log('Request method:', req.method);
    console.log('Request headers:', Object.fromEntries(req.headers.entries()));
    
    if (req.method !== 'POST') {
      throw new Error('Only POST method allowed');
    }

    const requestBody = await req.json();
    console.log('Request body received:', JSON.stringify(requestBody, null, 2));
    
    const { message, conversationHistory } = requestBody;
    
    if (!message || typeof message !== 'string') {
      throw new Error('Message is required and must be a string');
    }

    console.log('Processing message:', message);
    console.log('Conversation history items:', conversationHistory?.length || 0);

    // Read the Gemini API key from environment variables
    const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
    
    if (!GEMINI_API_KEY) {
      throw new Error('Missing GEMINI_API_KEY environment variable');
    }

    console.log('Gemini API key loaded from environment.');

    // Create the prompt for Gemini
    const systemPrompt = `"You are an advanced AI construction project assistant. Your goal is to understand the user's request and provide concise, actionable, and professional assistance. You are integrated into a system that can perform actions like: drafting emails, making calls (scheduling/summarizing), generating reports, scheduling meetings, setting reminders, and sending alerts.

When responding:
- If the user's request implies one of these actions, clearly state the action you are taking or suggesting (e.g., "Okay, I can help you draft that email," or "I will generate a report based on your criteria.").
- If the request is for information, provide it clearly and concisely.
- If the request is ambiguous, ask for clarification.
- Maintain a professional and helpful tone.
- Base your responses on the context of the current conversation if history is provided."`;
    
    let constructedPrompt = systemPrompt;

    if (conversationHistory && Array.isArray(conversationHistory)) {
      for (const entry of conversationHistory) {
        if (entry.role === 'user') {
          constructedPrompt += `

User: ${entry.content}`;
        } else if (entry.role === 'assistant') {
          constructedPrompt += `

Assistant: ${entry.content}`;
        }
      }
    }

    constructedPrompt += `

User: ${message}`; // The current user's message
    constructedPrompt += `

Assistant:`; // Prompt Gemini to generate the assistant's response
    
    console.log('Calling Gemini API with constructed prompt length:', constructedPrompt.length);

    // Call Gemini API
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GEMINI_API_KEY}`;
    
    const requestPayload = {
      contents: [{
        parts: [{
          text: constructedPrompt
        }]
      }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 1024,
      }
    };

    console.log('Sending request to Gemini:', JSON.stringify(requestPayload, null, 2));

    const geminiResponse = await fetch(geminiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestPayload)
    });

    console.log('Gemini response status:', geminiResponse.status);
    console.log('Gemini response headers:', Object.fromEntries(geminiResponse.headers.entries()));

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error('Gemini API error response:', errorText);
      throw new Error(`Gemini API error: ${geminiResponse.status} - ${errorText}`);
    }

    const responseText = await geminiResponse.text();
    console.log('Raw Gemini response:', responseText);

    const data = JSON.parse(responseText);
    console.log('Parsed Gemini response:', JSON.stringify(data, null, 2));
    
    const aiResponse = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!aiResponse) {
      console.error('No response text found in Gemini response structure');
      throw new Error('No response generated by Gemini');
    }

    console.log('Extracted AI response:', aiResponse);
    console.log('=== EDGE FUNCTION COMPLETED SUCCESSFULLY ===');

    return new Response(
      JSON.stringify({ 
        response: aiResponse,
        debug: {
          messageLength: message.length,
          responseLength: aiResponse.length,
          timestamp: new Date().toISOString()
        }
      }),
      { 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );

  } catch (error) {
    console.error('=== EDGE FUNCTION ERROR ===');
    console.error('Error type:', error.constructor.name);
    console.error('Error message:', error.message);
    console.error('Error stack:', error.stack);
    
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Unknown error occurred',
        errorType: error.constructor.name,
        timestamp: new Date().toISOString(),
        details: 'Check the edge function logs for more information'
      }),
      { 
        status: 500,
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );
  }
});
